version: '2'

services:
    nginx:
        image: nginx:1.19.0
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ../:/var/www/html
            - ./docker/nginx-1.19.0/configs/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        environment: 
            - VIRTUAL_HOST={your-domain.com}
            - VIRTUAL_PORT=8080
        networks: 
            - laravel

    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./docker/jwilder-nginx-proxy-latest/certs:/etc/nginx/certs
        networks:
            - laravel

    mysql:
        image: mysql:8.0.20
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks: 
            - laravel
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        container_name: phpmyadmin
        ports: 
            - "8081:80"
        links:
            - mysql:db
        environment:
            UPLOAD_LIMIT: 9999999999
        networks:
            - laravel

    php:
        build:
            context: ./docker/php-7.4-fpm/images
            dockerfile: Dockerfile
        container_name: php
        ports: 
            - "9000:9000"
        volumes: 
            - ../:/var/www/html
        networks: 
            - laravel

volumes:
    {your-project}-mysqldata:            

networks:
    laravel:
